### PR TITLE
OVN kubernetes does not require kube-proxy

### LINKED ISSUE #329: OVN Kubernetes CNI does not require kube-proxy
OVN kuberentes CNI plugin does not require kube-proxy, but at present kube-install-ovn playbook does not stop the kube-proxy daemonset. Running kube-proxy daemonset is useless, so installation playbook should stop those containers running kube-proxy.

### PR DESCRIPTION
**Pull request by vishnoianil**
So stop the kube-proxy daemon once OVN kuberentes CNI
is deployed and up

Resolves: #329
Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>

### CODE REVIEW

**Comment by vishnoianil** [comment]
@s1061123 @dougbtv PTAL, thanks

**Review by s1061123 — CHANGES_REQUESTED** [review]
Could you please take care of an asnible-lint error in CI result?
https://travis-ci.org/github/redhat-nfvpe/kube-ansible/builds/661329844?utm_source=github_status&utm_medium=notification

**Comment by vishnoianil** [comment]
> Could you please take care of an asnible-lint error in CI result?
> https://travis-ci.org/github/redhat-nfvpe/kube-ansible/builds/661329844?utm_source=github_status&utm_medium=notification

@s1061123 Done and fixed.

**Comment by s1061123** [comment]
LGTM!

**Pull request merged**
